# Generated by Django 3.1.5 on 2021-02-22 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='update date')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_post', to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Invalid title. letters, numbers, dash and space only'}, help_text='150 characters or fewer. Letters, number, dash and space only.', max_length=150, validators=[django.core.validators.RegexValidator(re.compile('^[-0-9a-zA-Z]*$'), code='invalid', message='Enter a valid title consisting of letters, number, - and space only.')], verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_of', to='feed.post')),
            ],
        ),
    ]
